'use strict';
const D=window.SESSIONDNA, names={running:'Course',cycling:'Vélo',swimming:'Natation',hiking:'Randonnée'}, objectives={ef:'Footing / EF',endurance_soutenue:'Endurance soutenue',seuil:'Seuil',vo2max:'VO₂ max',recuperation:'Récupération',vitesse:'Vitesse',competition:'Compétition'};
const $=id=>document.getElementById(id), fmt=(n,d=1)=>n==null?'—':Number(n).toLocaleString('fr-FR',{maximumFractionDigits:d}), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n};
const activities=[...D.activities].sort((a,b)=>b.start_utc.localeCompare(a.start_utc));let limit=30;
$('freshness').textContent='Historique actualisé le '+new Date(D.generated_utc).toLocaleString('fr-FR')+' · '+D.errors.length+' erreurs/exclusions · '+(D.quality?.review||0)+' séances à revoir.';
for(const sport of ['running','cycling','swimming']){const rows=activities.filter(a=>a.sport===sport),card=el('article',null,'card');card.append(el('span',names[sport]),el('strong',rows.length+' séances'),el('small',fmt(rows.reduce((s,a)=>s+(a.timer_min||0),0)/60)+' h enregistrées'));$('totals').append(card)}
const weeks=[...new Set(D.weeks.map(w=>w.week))].sort().slice(-12), max=Math.max(1,...weeks.map(w=>D.weeks.filter(x=>x.week===w).reduce((s,x)=>s+x.timer_min,0)));
$('weeks').append(el('p','Vert : course · Bleu : vélo · Violet : natation · Ocre : randonnée','legend'));
for(const week of weeks){const line=el('div',null,'week'),bar=el('div',null,'bar'),rows=D.weeks.filter(w=>w.week===week);let total=0;for(const s of ['running','cycling','swimming','hiking']){const minutes=rows.filter(w=>w.sport===s).reduce((a,w)=>a+w.timer_min,0);total+=minutes;const part=el('span',null,s);part.style.width=(100*minutes/max)+'%';part.title=names[s]+': '+fmt(minutes/60)+' h';bar.append(part)}line.append(el('span',week),bar,el('span',fmt(total/60)+' h'));$('weeks').append(line)}
function render(){const query=$('search').value.trim().toLowerCase(),sport=$('sport').value,rows=activities.filter(a=>(!sport||a.sport===sport)&&(!query||(a.start_utc+' '+a.filename).toLowerCase().includes(query)));$('list').replaceChildren();$('count').textContent=rows.length+' séances trouvées';for(const a of rows.slice(0,limit)){const b=el('button');b.type='button';b.append(el('span',new Date(a.start_utc).toLocaleString('fr-FR')+' · '+(names[a.sport]||a.sport)),el('small',fmt(a.distance_km)+' km · '+fmt(a.timer_min)+' min'+(a.human_objective?' · '+(objectives[a.human_objective]||a.human_objective):'')));b.addEventListener('click',()=>detail(a));$('list').append(b)}$('more').hidden=limit>=rows.length}
function chart(parent,points,column,title,color){const values=points.map(p=>p[column]).filter(Number.isFinite);if(!values.length)return;parent.append(el('h3',title));const canvas=el('canvas',null,'chart');canvas.width=1000;canvas.height=240;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',title+' en fonction du temps écoulé');parent.append(canvas);const ctx=canvas.getContext('2d'),lo=Math.min(...values),hi=Math.max(lo+1,...values),xmin=points[0][0],xmax=Math.max(xmin+1,points[points.length-1][0]);ctx.strokeStyle='#d5dfdc';ctx.strokeRect(55,15,920,190);ctx.fillStyle='#365259';ctx.font='16px system-ui';ctx.fillText(fmt(hi),2,25);ctx.fillText(fmt(lo),2,205);ctx.fillText('0',55,230);ctx.fillText(fmt(xmax)+' min écoulées',790,230);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();let connected=false;for(const p of points){if(!Number.isFinite(p[column])){connected=false;continue}const x=55+(p[0]-xmin)/(xmax-xmin)*920,y=205-(p[column]-lo)/(hi-lo)*190;if(connected)ctx.lineTo(x,y);else ctx.moveTo(x,y);connected=true}ctx.stroke()}
function detail(a){const box=$('detail');box.hidden=false;box.replaceChildren(el('h2',(names[a.sport]||a.sport)+' · '+new Date(a.start_utc).toLocaleDateString('fr-FR')),el('small',a.filename));const back=el('button','Revenir aux séances');back.type='button';back.addEventListener('click',()=>$('list').scrollIntoView({behavior:'smooth'}));const backRow=el('p');backRow.append(back);box.append(backRow);const metrics=el('div',null,'metrics');for(const [label,value] of [['Distance',fmt(a.distance_km)+' km'],['Temps chronométré',fmt(a.timer_min)+' min'],['Temps écoulé',fmt(a.elapsed_min)+' min'],['FC moyenne FIT',fmt(a.hr_session_mean,0)+' bpm']]){const item=el('div',label);item.append(el('b',value));metrics.append(item)}box.append(metrics);const facts=[];
if(a.human_objective)facts.push('Ton annotation : '+(objectives[a.human_objective]||a.human_objective)+'. Format : '+(a.human_format||'non renseigné')+'.');
if(a.model_prediction)facts.push('Suggestion expérimentale du modèle : '+(objectives[a.model_prediction.objective]||a.model_prediction.objective)+'. Lot '+a.model_prediction.split+' du jeu initial ; seuls EF, endurance soutenue et seuil sont possibles.');
if(a.duration_delta_s>2)facts.push('Le temps écoulé dépasse le chronomètre de '+fmt(a.duration_delta_s,0)+' secondes. Ce décalage seul ne localise pas les pauses.');
if(a.historical_detection){const h=a.historical_detection;facts.push('Analyse v2 du lot initial : '+fmt(h.n_pauses,0)+' pauses timer ('+fmt(h.pause_s,0)+' s) et '+fmt(h.n_v2,0)+' blocs rapides proposés. Ces blocs ne sont pas des catégories physiologiques.');}
if(a.sport==='running'){if(a.brick_candidate){const b=a.brick_candidate;facts.push('Un vélo précède cette course de '+fmt(b.transition_min)+' min ('+fmt(b.bike_timer_min)+' min de vélo). Candidat brick à confirmer.')}else facts.push('Aucun vélo trouvé dans les 30 minutes avant ce départ. Cela ne prouve pas l’absence de brick.');const tag=a.human_tags?.brick_run;if(tag)facts.push('Ton annotation brick : '+tag+'.');if(a.speed_late_early_ratio!=null)facts.push('Rapport de vitesse médiane dernier/premier tiers des points à plus de 5 km/h : '+fmt(a.speed_late_early_ratio,2)+'. Ce n’est pas une mesure de fatigue.');}
if(a.sport==='cycling')facts.push('Puissance moyenne du résumé FIT : '+fmt(a.power_session_mean,0)+' W. Cadence moyenne : '+fmt(a.cadence_session_mean,0)+' tr/min.');
if(a.sport==='swimming'){facts.push(a.active_lengths?fmt(a.active_lengths,0)+' longueurs actives · bassin de '+fmt(a.pool_length_m,0)+' m · '+fmt(a.rest_lengths,0)+' segments de repos.':'Pas de longueurs exploitables : analyse à partir du résumé de séance.');if(a.pace_active_100m_s!=null)facts.push('Allure des longueurs actives : '+fmt(a.pace_active_100m_s,0)+' s/100 m, hors segments de repos.');}
facts.push(...a.issues);const ul=el('ul');facts.forEach(f=>ul.append(el('li',f)));box.append(ul);const pts=D.profiles[a.id]||[];chart(box,pts,1,'Vitesse (km/h)','#299c79');chart(box,pts,2,'Fréquence cardiaque (bpm)','#c05050');if(a.sport==='cycling')chart(box,pts,3,'Puissance (W)','#387ebe');box.append(el('p','Courbes moyennées par fenêtres de 15 secondes ; les trous ne sont pas interpolés.'));box.scrollIntoView({behavior:'smooth'});box.focus({preventScroll:true})}
const m=D.model_metrics;$('model').textContent=m?'Premier essai expérimental : '+m.train_n+' séances d’apprentissage, '+m.test_n+' séances de test, '+Math.round(m.metrics.accuracy*m.test_n)+' correctement classées. Ces chiffres concernent uniquement cette petite sélection annotée. Les suggestions sont affichées pour le jeu initial de 73 courses ; le nouvel historique reste à évaluer. Consulte le rapport sport_model pour les erreurs et le protocole.':'Aucun modèle entraîné chargé.';
if(D.has_annotation_form){const p=el('p'),a=el('a','Ouvrir les fiches d’annotation du jeu initial');a.href='annotation.html';a.target='_blank';a.rel='noopener';p.append(a);$('model').parentNode.append(p);if(D.has_annotation_export){const note=el('p','Si tes réponses ne sont pas présentes dans ce navigateur, importe dans les fiches cet export conservé : '),link=el('a','mes annotations');link.href='annotations_sport.json';link.download='annotations_sport.json';note.append(link);$('model').parentNode.append(note)}}
$('sport').addEventListener('change',()=>{limit=30;render()});$('search').addEventListener('input',()=>{limit=30;render()});$('more').addEventListener('click',()=>{limit+=30;render()});render();
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
