(() => {
  'use strict';
  const data=window.SESSIONDNA,P=window.SessionPlanner,cal=data.calendar,host=document.getElementById('calendar'),sel=document.getElementById('training-week');
  const el=(tag,text)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;return n;};
  if(!cal){host.append(el('h2','Mes cours'),el('p','Aucun calendrier importé.'));return;}
  const key='sessiondna-planning-v1';let state={settings:{wake:'',bed:'',commute:'',before:'',after:'',swimExtra:''},weeks:{}},blocked=false;
  try{const saved=localStorage.getItem(key);if(saved){const x=JSON.parse(saved);if(!x.settings||!x.weeks||typeof x.weeks!=='object')throw Error('format invalide');state=x;}}catch(e){blocked=true;}
  const defaults=data.planning_defaults||{},pool=defaults.pool;
  if(!state.settings.wake)state.settings.wake=defaults.wake||'';
  if(!state.settings.bed)state.settings.bed=defaults.bed||'';
  const save=()=>{if(blocked)throw Error('Ancienne sauvegarde illisible : exporte tes données avant de réinitialiser le stockage.');localStorage.setItem(key,JSON.stringify(state));window.dispatchEvent(new Event('planning-change'));};
  const plan=()=>data.training_weeks.find(w=>w.plan.week_start===sel.value);
  const times=()=>state.weeks[plan().manifest.source_sha256]||{};
  const status=el('p');status.setAttribute('role','status');
  host.append(el('span','COURS & ORGANISATION'),el('h2','Trouver ma place dans la semaine'),el('p',`${cal.events.length} événements · export importé le ${new Date(cal.imported_utc).toLocaleDateString('fr-FR',{timeZone:'Europe/Paris'})}. Mise à jour manuelle ; un jour sans cours dans cet export ne garantit pas sa disponibilité.`));
  for(const w of cal.warnings)host.append(el('p',w));
  if(defaults.sleep_note)host.append(el('p',defaults.sleep_note));
  if(pool){const info=el('details');info.append(el('summary',pool.name));info.append(el('p',pool.scope+' Sortie de l’eau '+pool.evacuation_min+' min avant fermeture ; marge vestiaire retenue : '+pool.changing_min+' min.'));const link=el('a','Horaires officiels, vérifiés le '+pool.checked);link.href=pool.source;link.target='_blank';link.rel='noopener noreferrer';info.append(link);host.append(info);}
  const details=el('details'),summary=el('summary','Mes horaires et mes marges');details.open=true;details.append(summary);
  details.append(el('p','Horaires en heure de Paris. Renseigne tes contraintes pour activer les propositions. La marge avant/après doit inclure préparation, trajet sportif, douche et repas si nécessaire. Les cours en ligne restent bloquants ; la marge de transport est appliquée à tous les cours par prudence.'));
  const form=el('form');form.className='feedback-form';const inputs={};
  for(const [k,title,type] of [['wake','Début de disponibilité après le réveil','time'],['bed','Fin de disponibilité avant le coucher','time'],['commute','Trajet cours, par sens (min)','number'],['before','Marge avant chaque séance (min)','number'],['after','Marge après chaque séance (min)','number'],['swimExtra','Temps supplémentaire piscine : récupérations, etc. (min)','number']]){const l=el('label',title),input=el('input');input.type=type;input.required=true;if(type==='number'){input.min=0;input.max=240;input.step=1;}input.value=state.settings[k]??'';inputs[k]=input;l.append(input);form.append(l);}
  const submit=el('button','Enregistrer mes contraintes');submit.type='submit';form.append(submit);details.append(form);host.append(details);
  host.append(el('p','Les propositions sont des essais de créneaux, sans validation sportive : horaires de piscine, lumière, repas et consignes du programme restent à vérifier. Aucune séance ne change de date. Les enchaînements liés sont à placer manuellement.'));
  const propose=el('button','Proposer des créneaux libres'),backup=el('button','Exporter mon organisation');host.append(propose,backup,status);const days=el('div');days.className='calendar-days';host.append(days);
  const restoreLabel=el('label','Restaurer une organisation (complète les horaires absents)'),restore=el('input');restore.type='file';restore.accept='.json,application/json';restoreLabel.append(restore);host.insertBefore(restoreLabel,days);
  restore.addEventListener('change',async()=>{try{const f=restore.files[0];if(!f)return;if(f.size>2e6)throw Error('Fichier trop volumineux');const payload=JSON.parse(await f.text());if(payload.schema_version!=='sessiondna.planning.v1'||!P.validate(payload.settings)||!payload.weeks||typeof payload.weeks!=='object'||Array.isArray(payload.weeks))throw Error('Sauvegarde invalide');const next=JSON.parse(JSON.stringify(state));let count=0;for(const [hash,entries] of Object.entries(payload.weeks)){const w=data.training_weeks.find(x=>x.manifest.source_sha256===hash);if(!w)throw Error('Programme absent : importer cette semaine avant ses horaires');if(!entries||typeof entries!=='object'||Array.isArray(entries))throw Error('Horaires invalides');const merged={...(next.weeks[hash]||{})};for(const [id,time] of Object.entries(entries)){if(!w.plan.sessions.some(s=>s.id===id)||!Number.isFinite(P.mins(time)))throw Error('Séance ou horaire invalide');if(!merged[id]){merged[id]=time;count++;}}next.weeks[hash]=merged;}if(!P.validate(next.settings))next.settings=payload.settings;if(blocked)throw Error('Sauvegarde existante illisible : restauration bloquée pour la préserver');localStorage.setItem(key,JSON.stringify(next));state=next;for(const [k,v] of Object.entries(inputs))v.value=state.settings[k];window.dispatchEvent(new Event('planning-change'));status.textContent=count+' horaires restaurés. Les horaires et contraintes déjà renseignés sont conservés.';render();}catch(e){status.textContent='Restauration refusée : '+e.message;}finally{restore.value='';}});
  function render(){
    days.replaceChildren();const w=plan();if(!w)return;const p=state.settings,valid=P.validate(p),ts=times();propose.disabled=!valid||blocked;
    for(let i=0;i<7;i++){const d=new Date(w.plan.week_start+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+i);const date=d.toISOString().slice(0,10),card=el('article');card.className='calendar-day';card.append(el('h3',d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'})));
      if(pool){const hours=pool.hours[d.getUTCDay()];card.append(el('p',date>=pool.valid_from&&date<=pool.valid_until&&hours?'Piscine : '+hours[0]+'–'+hours[1]+' (sortie eau '+P.clock(P.mins(hours[1])-pool.evacuation_min)+')':'Piscine : horaires à revérifier'));}
      const cs=P.courses(cal.events,date);if(!cs.length)card.append(el('p','Aucun cours dans cet export'));
      for(const c of cs){const n=el('div');n.className='course-card';n.append(el('strong',P.clock(c.start)+'–'+P.clock(c.end)),el('p',c.title),el('small',c.location));card.append(n);}
      for(const s of w.plan.sessions.filter(s=>s.date===date)){const box=el('div');box.className='schedule-card';box.append(el('strong',s.title),el('p',s.planned_duration_min+' min annoncées'));const label=el('label','Début de séance'),time=el('input');time.type='time';time.value=ts[s.id]||'';time.disabled=blocked;label.append(time);box.append(label);
        time.addEventListener('change',()=>{try{const next={...times()};if(time.value)next[s.id]=time.value;else delete next[s.id];state.weeks[w.manifest.source_sha256]=next;save();status.textContent='Horaire enregistré dans ce navigateur.';render();}catch(e){status.textContent=e.message;}});
        if(ts[s.id]){if(valid){const problems=P.conflicts(s,ts[s.id],p,cal.events,w.plan.sessions,ts,pool);const msg=el('p',problems.length?'Conflit : '+problems.join(' · '):'Pas de conflit détecté avec les cours, marges et séances placées.');msg.className=problems.length?'conflict':'available';box.append(msg);}else box.append(el('p','Renseigne les contraintes pour vérifier cet horaire.'));}
        if(s.scheduling.linked_session_id||w.plan.sessions.some(o=>o.scheduling.linked_session_id===s.id))box.append(el('p','Enchaînement lié : vérifier ensemble l’ordre et la transition.'));
        const constraints=el('details');constraints.append(el('summary','Consignes de placement'));for(const c of s.scheduling.constraints||[])constraints.append(el('p',c));box.append(constraints);card.append(box);
      }days.append(card);
    }
  }
  form.addEventListener('submit',e=>{e.preventDefault();const settings=Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value]));if(!P.validate(settings)){status.textContent='Vérifie les valeurs : début avant fin de journée (coucher après minuit non pris en charge).';return;}try{state.settings=settings;save();status.textContent='Contraintes enregistrées. Les horaires existants sont conservés et leurs conflits recalculés.';render();}catch(e){status.textContent=e.message;}});
  propose.addEventListener('click',()=>{try{const w=plan(),p=state.settings,next={...times()};let count=0,unplaced=0;for(const s of w.plan.sessions){if(next[s.id])continue;if(s.scheduling.linked_session_id||w.plan.sessions.some(o=>o.scheduling.linked_session_id===s.id)){unplaced++;continue;}let candidates=[];if(s.scheduling.preferred_time)candidates.push(s.scheduling.preferred_time);for(let t=Math.ceil((P.mins(p.wake)+Number(p.before))/15)*15;t<P.mins(p.bed);t+=15)candidates.push(P.clock(t));const chosen=candidates.find(t=>!P.conflicts(s,t,p,cal.events,w.plan.sessions,next,pool).length);if(chosen){next[s.id]=chosen;count++;}else unplaced++;}state.weeks[w.manifest.source_sha256]=next;save();status.textContent=`${count} propositions enregistrées, à vérifier ; ${unplaced} séances restent à placer. Les horaires déjà saisis sont conservés.`;render();}catch(e){status.textContent=e.message;}});
  backup.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({schema_version:'sessiondna.planning.v1',...state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='organisation-sessiondna.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  if(blocked)status.textContent='Sauvegarde d’organisation illisible. Modification bloquée pour la préserver.';
  sel.addEventListener('change',render);render();
})();
